language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
notifications:
  slack: 
    secure: MJMUiM6TxIbwsvJN4jU1xAVSFDlBp0vDxdO7CtdYqMeRY9Vndt0oYig4mcLxDbVm+SyWrDrfUFT1AWYPD4q0tocPjaYUZVr7vwaJr0GHiHNPL9cNZJrqI0T6TQOU857i9hkAjXgMY1/UeU5PJRf/2bCBJ24jWZH3S/xYGwc9w1CbbdCVHQtk3RHbZSLcXghPG68iDjj/E+zb4SfAbuMc4OcrdfOMfeWBnK/9Qmkf/updlD3AyZtsmbSYLoaH11FF8SYUYvmU8jOEEB7hboSmVSYDSGOEGjJL1SE6YV80V/b/lSle4p0TTqCbqXLntHqkQP4AnKTcFjxOKcC+QfCYCUJumbe818WtLnngoCVW/t2ILh/shprQSqmjjQOWYPQWI53M6VTlrrVwEE9EczPFjy2Vf4gt+KYPZLkpC7FJNJMDc+PlcWIaCsTFQVlxAhxyg3Nxsw3iN/2FRwJCsDq5TVPnHv2MEXLedlBuefZ2KrnpSfGO9mwTF9zBozlapKb+2lww5X+LMAJtnEj9UXLWw7ObQHOTHE/UcUTXn1a2pXyjpga9fxDES2/9B8wK4eNJWYmz8MdPWYO155Y4s/AY/V+8il8i2+cDAqvGuLrLeHCZBn2qL7Ip2xysIEPZUjIpxrelmNaiDfhjsSaKnkBGoyinZjNMptGQARrRLusBvyk=
