language: python
python:
- '3.4'
- '3.5'
script: python -m unittest
notifications:
  slack: 
    secure: HN1m7BzvZUx11QnWcXkiQEgG5K/3hatJ0v3p093znfIQvFa0ka3/URNtnrZqiPTTRLULpa+QdMMvhYHeRUVad0jSWQZsxLLh7I7ZSjdRDnJ8xZWP+r0GiAL2UMP6DoAQRZd9b+uvK+O6xH23efn7qVSpXVTLWJigOMiZ4eDSknBD2CoSEfTZZeSLRxY7CJUKsQ1jF/mlYw3wNE22Msb+s1It2zoOCYiSPxx6Z9OuVRPatGFSVWsaqsFwA8PEv4YvM60WSEM9doCjHqXpOvLPreUIY/Ma/DRdOCo23m2FXaY5pd5URSF0K5bC8Z/V19fw3YuDOQANh7fx0ZYUJ+U0bDe3h8Ys5vMJmb2TBt+oYpfkLEopJRvPRkdIeqbL2VUGJSc1VOI92S0uesTZBp/5ExHNM1FmLIXEOJVIwGRiDUSOj4KnglYG08H/lOSJpKeMxY7Wzjbc/z9F0nuDcd7sSRplHIuGPlTIFyj2SiS/z24LqR33dumKpTo3VR8Y6refHuv3dO/ply+NJub30A49iNEF5Ek4KZha4JN03HGdUEXkKacQbUIeSJqO8YQd8NC664ikazYlu2Vom2uEMnBOwDAKqWto/dk56rotpRCe2QECcqxYb4VsDQbNjQjEmLE7pxUT1E9nbcTJQ2sB21wDKrosmnwfTM9rzCp8o9Gu8Uc=